### ISSUE TITLE
Consider removing the `--no-verify` flag from `git fixup`

### ISSUE THREAD

**Issue by kkom** [nvie/git-toolbelt#14]
Hey @nvie!

I see that in https://github.com/nvie/git-toolbelt/commit/9ec21b6d684db7d10c9e3df907082afe93023fdf you added the `--no-verify` flag to "adjust the fixup command to your liking"

Would you be open to reconsidering this decision? We rely heavily on `git fixup` in our one-commit-per-branch workflow ( https://github.com/kkom/code-review ). We recently added pre-commit hooks, and in our case it would be reasonable to run them whenever a commit is amended. I.e. we think of skipping verification as an exception rather than rule.

If https://github.com/nvie/git-toolbelt/commit/9ec21b6d684db7d10c9e3df907082afe93023fdf was reverted, would it still be possible to run `git fixup --no-verify` in exceptional cases? If no, is this something I could submit a PR for? Would it be a reasonable compromise you think?

Please let me know what do you think! :)

Best,
Konrad

PS: Thanks again for creating the toolbelt, it's super useful for us at Hack Partners. :)

**Comment by nvie** [comment]
Yeah, I think not using `--no-verify` here is the correct thing to do. Ironically, I added this flag because a project I was working adopted a pre-commit hook that was super slow to run, and it broke my personal work flow, so this was a selfish change. Main reason for hacking in the `--no-verify` flag at this level is that [Git does not support overwriting "built-ins" with aliases](https://stackoverflow.com/questions/3538774/is-it-possible-to-override-git-command-by-git-alias), which is a sane choice, but pretty annoying in this case.

But yes, you're right and git-toolbelt should indeed respect the pre-commit hook.  I'll hack around this in a different way for this project, and keep git-toolbelt's implementation sane — thanks for reporting 👍

**Comment by nvie** [comment]
I just published this as v1.2.2.

**Comment by kkom** [comment]
Thanks @nvie!

Oh, so ` "$@"` at the end makes it possible to pass additional flags if need be! Neat!

**Comment by nvie** [comment]
> Oh, so ` "$@"` at the end makes it possible to pass additional flags if need be! Neat!

Yes, that's what I'm using now in my wrapper script.
