### ISSUE TITLE
git cleanup with flags seem to just print the helpscreen.

### ISSUE THREAD

**Issue by kitsunde** [nvie/git-toolbelt#59]
I did a homebrew install, and I have coreutils. Not sure why but I'm just getting this:

```bash
➜  src git:(master) git cleanup -n
usage: git cleanup [-lr] [-nsvh]

Deletes all branches that have already been merged into the main branch.
Removes those branches both locally and in the origin remote.  Will be
most conservative with deletions.

Options:
-l    Remove local branches
-r    Remove remote branches (in `origin`)
-n    Dry-run
-s    Also consider squash merges (implies -l)
-v    Be verbose (show what's skipped)
-h    Show this help
```

I was trying to understand if I could set branches to skip in config since I don't want it to delete `origin/release` or `origin/main`.

**Comment by nvie** [comment]
Hi @kitsunde — this is working as intended. The issue is that you need to specify either `-l` or `-r` (or both).

![Screen Shot 2023-06-23 at 14 07 15@2x](https://github.com/nvie/git-toolbelt/assets/83844/ede5bfe0-8993-4b8f-94d5-9e523f02fe5d)

These flags define whether to delete branches locally or remotely. I wasn't comfortable picking a default for a destructive action like this, that's why those flags must be specified. Hope that helps to explain.

**Comment by nvie** [comment]
Updated the help text to better explain that in 16f6792de42d9c3ec93b0d61e31acff132d301a2 — thanks for the report! 👍
